all: SieveOfEratosthenes gen/genRand train

FastExponentiation: SieveOfEratosthenes.cpp
	./DbgCompile.sh SieveOfEratosthenes

gen/genRand: gen/genRand.cpp
	./DbgCompile.sh gen/genRand
	
train: train.cpp
	./DbgCompile.sh train