
all: IntervalIntervalAssignPlus brute-force gen/genRand

IntervalIntervalAssignPlus: IntervalIntervalAssignPlus.cpp
	./DbgCompile.sh IntervalIntervalAssignPlus
brute-force: brute-force.cpp
	./DbgCompile.sh brute-force
gen/genRand: gen/genRand.cpp
	./DbgCompile.sh gen/genRand
	