all: CountingSort gen/genRand train stl-check

CountingSort: CountingSort.cpp
	./DbgCompile.sh CountingSort

stl-check: stl-check.cpp
	./DbgCompile.sh stl-check

gen/genRand: gen/genRand.cpp
	./DbgCompile.sh gen/genRand
	
train: train.cpp
	./DbgCompile.sh train