
IntervalIntervalPlusMax: IntervalIntervalPlusMax.cpp
	./DbgCompile.sh IntervalIntervalPlusMax
brute-force: brute-force.cpp
	./DbgCompile.sh brute-force
gen/genRand: gen/genRand.cpp
	./DbgCompile.sh gen/genRand
	