all: AhoCorasick gen/genRand train brute-force

AhoCorasick: AhoCorasick.cpp
	./DbgCompile.sh AhoCorasick

brute-force: brute-force.cpp
	./DbgCompile.sh brute-force

gen/genRand: gen/genRand.cpp
	./DbgCompile.sh gen/genRand

train: train.cpp
	./DbgCompile.sh train