all: KMP KMP.2 gen/genRand brute-force

KMP: KMP.cpp
	./DbgCompile.sh KMP

KMP.2: KMP.2.cpp
	./DbgCompile.sh KMP.2

brute-force: brute-force.cpp
	./DbgCompile.sh brute-force

gen/genRand: gen/genRand.cpp
	./DbgCompile.sh gen/genRand