all: MergeSort gen/genRand train stl-check

MergeSort: MergeSort.cpp
	./DbgCompile.sh MergeSort

stl-check: stl-check.cpp
	./DbgCompile.sh stl-check

gen/genRand: gen/genRand.cpp
	./DbgCompile.sh gen/genRand
	
train: train.cpp
	./DbgCompile.sh train