
IntervalIntervalPlusPlus: IntervalIntervalPlusPlus.cpp
	./DbgCompile.sh IntervalIntervalPlusPlus
brute-force: brute-force.cpp
	./DbgCompile.sh brute-force
gen/genRand: gen/genRand.cpp
	./DbgCompile.sh gen/genRand
	