all: SegmentIntersection gen/genRand train 

SegmentIntersection: SegmentIntersection.cpp
	./DbgCompile.sh SegmentIntersection

gen/genRand: gen/genRand.cpp
	./DbgCompile.sh gen/genRand
	
train: train.cpp
	./DbgCompile.sh train