all: QuickSort gen/genRand train stl-check

QuickSort: QuickSort.cpp
	./DbgCompile.sh QuickSort

stl-check: stl-check.cpp
	./DbgCompile.sh stl-check

gen/genRand: gen/genRand.cpp
	./DbgCompile.sh gen/genRand
	
train: train.cpp
	./DbgCompile.sh train