all: ExtendedEuclideanAlgorithm gen/genRand

ExtendedEuclideanAlgorithm: ExtendedEuclideanAlgorithm.cpp
	./DbgCompile.sh ExtendedEuclideanAlgorithm

gen/genRand: gen/genRand.cpp
	./DbgCompile.sh gen/genRand