all: ExtendedEuclideanAlgorithm gen/genRand train

ExtendedEuclideanAlgorithm: ExtendedEuclideanAlgorithm.cpp
	./DbgCompile.sh ExtendedEuclideanAlgorithm

gen/genRand: gen/genRand.cpp
	./DbgCompile.sh gen/genRand

train: train.cpp
	./DbgCompile.sh train