all: FastExponentiation gen/genRand train brute-force

FastExponentiation: FastExponentiation.cpp
	./DbgCompile.sh FastExponentiation

brute-force: brute-force.cpp
	./DbgCompile.sh brute-force

gen/genRand: gen/genRand.cpp
	./DbgCompile.sh gen/genRand
	
train: train.cpp
	./DbgCompile.sh train