all: RMQ brute-force gen/genRand train

RMQ: RMQ.cpp
	./DbgCompile.sh RMQ

brute-force: brute-force.cpp
	./DbgCompile.sh brute-force

gen/genRand: gen/genRand.cpp
	./DbgCompile.sh gen/genRand

train: train.cpp
	./DbgCompile.sh train